jenkins.sh: fix race condition against process substitution
Sometimes, the gsutil command fails with

    CommandException: No URLs matched: /dev/fd/63

where /dev/fd/63 is most likely the file handle used by Bash's process
substitution. So, use STDIN instead.

We also remove the -m (multithreaded) flag because gsutil's help page
warns that it is incompatible:

    Note: Streaming transfers are not allowed when the top-level gsutil -m flag
    is used.

(this is for gsutil version 4.47).