Finish release.SetBuildVersion() implementation
This allows us to use the new `SetBuildVersion` golang API to remove the
bash-implementation later on as well as transform `find_green_build`
(bash) to golang. The API can be used like this:

```go
release.NewBuildVersionClient().SetBuildVersion(git.Master, "", nil)
```

Which will result in:
```
INFO Setting build version for branch "master"
INFO Changing master branch to "release-master"
INFO Retrieving testgrid configuration
INFO Got testgrid jobs for branch "release-master": [ci-kubernetes-build ci-kubernetes-build-fast ci-kubernetes-conformance-kind-ga-only ci-kubernetes-e2e-gce-device-plugin-gpu ci-kubernetes-e2e-gce-master-new-gci-kubectl-skew ci-kubernetes-e2e-gci-gce ci-kubernetes-e2e-gci-gce-alpha-features ci-kubernetes-e2e-gci-gce-ingress ci-kubernetes-e2e-gci-gce-reboot ci-kubernetes-e2e-gci-gce-scalability ci-kubernetes-e2e-ubuntu-gce-containerd ci-kubernetes-gce-conformance-latest ci-kubernetes-integration-master ci-kubernetes-kind-e2e-parallel ci-kubernetes-kind-ipv6-e2e-parallel ci-kubernetes-node-kubelet ci-kubernetes-verify-master periodic-kubernetes-bazel-build-master periodic-kubernetes-bazel-test-master]
INFO Getting ci-kubernetes-build build results from GCS
INFO Getting ci-kubernetes-build-fast build results from GCS
INFO Getting ci-kubernetes-conformance-kind-ga-only build results from GCS
CommandException: No URLs matched: gs://kubernetes-jenkins/logs/ci-kubernetes-conformance-kind-ga-only/jobResultsCache.json
CommandException: 1 file/object could not be transferred.
WARN Skipping unavailable remote path gs://kubernetes-jenkins/logs/ci-kubernetes-conformance-kind-ga-only/jobResultsCache.json
INFO Getting ci-kubernetes-e2e-gce-device-plugin-gpu build results from GCS
INFO Getting ci-kubernetes-e2e-gce-master-new-gci-kubectl-skew build results from GCS
INFO Getting ci-kubernetes-e2e-gci-gce build results from GCS
INFO Getting ci-kubernetes-e2e-gci-gce-alpha-features build results from GCS
INFO Getting ci-kubernetes-e2e-gci-gce-ingress build results from GCS
INFO Getting ci-kubernetes-e2e-gci-gce-reboot build results from GCS
INFO Getting ci-kubernetes-e2e-gci-gce-scalability build results from GCS
INFO Getting ci-kubernetes-e2e-ubuntu-gce-containerd build results from GCS
INFO Getting ci-kubernetes-gce-conformance-latest build results from GCS
INFO Getting ci-kubernetes-integration-master build results from GCS
CommandException: No URLs matched: gs://kubernetes-jenkins/logs/ci-kubernetes-integration-master/jobResultsCache.json
CommandException: 1 file/object could not be transferred.
WARN Skipping unavailable remote path gs://kubernetes-jenkins/logs/ci-kubernetes-integration-master/jobResultsCache.json
INFO Getting ci-kubernetes-kind-e2e-parallel build results from GCS
CommandException: No URLs matched: gs://kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/jobResultsCache.json
CommandException: 1 file/object could not be transferred.
WARN Skipping unavailable remote path gs://kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/jobResultsCache.json
INFO Getting ci-kubernetes-kind-ipv6-e2e-parallel build results from GCS
CommandException: No URLs matched: gs://kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/jobResultsCache.json
CommandException: 1 file/object could not be transferred.
WARN Skipping unavailable remote path gs://kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/jobResultsCache.json
INFO Getting ci-kubernetes-node-kubelet build results from GCS
INFO Getting ci-kubernetes-verify-master build results from GCS
CommandException: No URLs matched: gs://kubernetes-jenkins/logs/ci-kubernetes-verify-master/jobResultsCache.json
CommandException: 1 file/object could not be transferred.
WARN Skipping unavailable remote path gs://kubernetes-jenkins/logs/ci-kubernetes-verify-master/jobResultsCache.json
INFO Getting periodic-kubernetes-bazel-build-master build results from GCS
CommandException: No URLs matched: gs://kubernetes-jenkins/logs/periodic-kubernetes-bazel-build-master/jobResultsCache.json
CommandException: 1 file/object could not be transferred.
WARN Skipping unavailable remote path gs://kubernetes-jenkins/logs/periodic-kubernetes-bazel-build-master/jobResultsCache.json
INFO Getting periodic-kubernetes-bazel-test-master build results from GCS
CommandException: No URLs matched: gs://kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/jobResultsCache.json
CommandException: 1 file/object could not be transferred.
WARN Skipping unavailable remote path gs://kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/jobResultsCache.json
INFO Trying version "v1.19.0-beta.2.790+9eced040142454" for build "1280834193957326848"
(*) Primary job (-) Secondary jobs

Job                                       Run                  Build  Date/Status
* build                                   1280849546682830849  790    2020-07-08T11:19:07Z
- build-fast                              1280851306898001920  790    SUCCEEDED
- conformance-kind-ga-only                1280851306898001920  790    NOT EXISTING
- e2e-gce-device-plugin-gpu               1280851306898001920  790    FAILED
- e2e-gce-master-new-gci-kubectl-skew     1280836458327838723  790    SUCCEEDED
- e2e-gci-gce                             1280839730467966977  790    SUCCEEDED
- e2e-gci-gce-alpha-features              1280839730467966977  790    FAILED
- e2e-gci-gce-ingress                     1280839730467966977  790    FAILED
- e2e-gci-gce-reboot                      1280842750345875457  790    SUCCEEDED
- e2e-gci-gce-scalability                 1280835703843852291  790    SUCCEEDED
- e2e-ubuntu-gce-containerd               1280835703843852291  790    FAILED
- gce-conformance-latest                  1280835703843852291  790    FAILED
- integration-master                      1280835703843852291  790    NOT EXISTING
- kind-e2e-parallel                       1280835703843852291  790    NOT EXISTING
- kind-ipv6-e2e-parallel                  1280835703843852291  790    NOT EXISTING
- node-kubelet                            1280825133354717185  790    SUCCEEDED
- verify-master                           1280825133354717185  790    NOT EXISTING
- periodic-kubernetes-bazel-build-master  1280825133354717185  790    NOT EXISTING
- periodic-kubernetes-bazel-test-master   1280825133354717185  790    NOT EXISTING

INFO Trying version "v1.19.0-beta.2.788+bf94f27e76c541" for build "1280818842905350144"
(*) Primary job (-) Secondary jobs

Job                                       Run                  Build  Date/Status
* build                                   1280818842905350144  788    2020-07-08T02:55:06Z
- build-fast                              1280822868766101504  788    SUCCEEDED
- conformance-kind-ga-only                1280822868766101504  788    NOT EXISTING
- e2e-gce-device-plugin-gpu               1280826643891359746  788    SUCCEEDED
- e2e-gce-master-new-gci-kubectl-skew     1280821107452022785  788    SUCCEEDED
- e2e-gci-gce                             1280822114932232193  788    SUCCEEDED
- e2e-gci-gce-alpha-features              1280808273120858112  788    SUCCEEDED
- e2e-gci-gce-ingress                     1280798710204207104  788    SUCCEEDED
- e2e-gci-gce-reboot                      1280826643891359744  788    SUCCEEDED
- e2e-gci-gce-scalability                 1280822114940620800  788    SUCCEEDED
- e2e-ubuntu-gce-containerd               1280810286281920512  788    SUCCEEDED
- gce-conformance-latest                  1280793677429477376  788    SUCCEEDED
- integration-master                      1280793677429477376  788    NOT EXISTING
- kind-e2e-parallel                       1280793677429477376  788    NOT EXISTING
- kind-ipv6-e2e-parallel                  1280793677429477376  788    NOT EXISTING
- node-kubelet                            1280809782663450628  788    SUCCEEDED
- verify-master                           1280809782663450628  788    NOT EXISTING
- periodic-kubernetes-bazel-build-master  1280809782663450628  788    NOT EXISTING
- periodic-kubernetes-bazel-test-master   1280809782663450628  788    NOT EXISTING
```

We can see that version `v1.19.0-beta.2.790+9eced040142454` did not succeed
because there were failing tests. Version `v1.19.0-beta.2.788+bf94f27e76c541` has all green builds,
whereas inexisting builds are skipped like before.

Signed-off-by: Sascha Grunert <sgrunert@suse.com>