Remove `_KUBERNETES_GCS_BUCKET` from build tags
The build tags have to match a pattern, which is not guaranteed for the
GCS bucket. Without this patch we will encounter the error:

```
ERROR: (gcloud.builds.submit) INVALID_ARGUMENT: invalid build: invalid
build tag
"gs://kubernetes-release-gcb/stage/v1.26.0-rc.0.63+f5b5dcadb2b5d4/1.26.0-rc.1/gcs-stage/1.26.0-rc.1":
must match format "^[\\w][\\w.-]{0,127}$"
```

Signed-off-by: Sascha Grunert <sgrunert@redhat.com>